<?php
echo "<nav id='cssmenu'>";
echo "<div class='logo'><a href='home.php'><image src='include/img/ehrms_logo.png' width='20%'/></a></div>";
//echo "<div id='head-mobile'></div>";
//echo "<div class='button'></div>";
echo "<ul>";
echo "<li class='".active('home')."'><a href='home.php'>HOME</a></li>";
echo "<li class='".active('about')."'><a href='about.php'>ABOUT</a></li>";
echo "<li class='".active('division_register').active('division_view').active('division_edit').active('division_delete').active('mandal_register').active('mandal_view').active('mandal_edit').active('mandal_delete').
active('polling_station_register').active('polling_station_view').active('polling_station_edit').active('polling_station_delete').active('ps_type_register').active('ps_type_view').active('ps_type_edit').active('ps_type_delete').
active('electionrole_register').active('electionrole_view').active('electionrole_edit').active('electionrole_delete').active('office_register').active('office_view').active('office_edit').active('office_delete').
active('emp_type_register').active('emp_type_view').active('emp_type_edit').active('emp_type_delete').active('emp_office_type_register').active('emp_office_type_view').active('emp_office_type_edit').active('emp_office_type_delete').
active('gender_register').active('gender_view').active('gender_edit').active('gender_delete').active('emp_dept_register').active('emp_dept_view').active('emp_dept_edit').active('emp_dept_delete')."'><a href='#'>MASTER TABLES</a>";
echo "<ul>";
      echo "<li class='".active('division_register').active('division_view').active('division_edit').active('division_delete')."'><a href='#'>Divisions</a>";
      echo "<ul>";
            echo "<li class='".active('division_register')."'><a href='division_register.php' Value='Register'>Add</a></li>";
            echo "<li class='".active('division_view')."'><a href='division_view.php' Value='View'>View</a></li>";
            echo "<li class='".active('division_edit')."'><a href='division_edit.php' Value='Edit'>Edit</a></li>";
            echo "<li class='".active('division_delete')."'><a href='division_delete.php' Value='Delete'>Delete</a></li>";
         echo "</ul>";
      echo "</li>";
      echo "<li class='".active('mandal_register').active('mandal_view').active('mandal_edit').active('mandal_delete')."'><a href='#'>Mandals</a>";
         echo "<ul>";
         echo "<li class='".active('mandal_register')."'><a href='mandal_register.php' Value='Register'>Add</a></li>";
         echo "<li class='".active('mandal_view')."'><a href='mandal_view.php' Value='View'>View</a></li>";
         echo "<li class='".active('mandal_edit')."'><a href='mandal_edit.php' Value='Edit'>Edit</a></li>";
         echo "<li class='".active('mandal_delete')."'><a href='mandal_delete.php' Value='Delete'>Delete</a></li>";
         echo "</ul>";
      echo "</li>";
      echo "<li class='".active('polling station_register').active('polling station_view').active('polling station_edit').active('polling station_delete')."'><a href='#'>Polling Stations</a>";
         echo "<ul>";
         echo "<li class='".active('polling_station_register')."'><a href='polling_station_register.php' Value='Register'>Add</a></li>";
         echo "<li class='".active('polling_station_view')."'><a href='polling_station_view.php' Value='View'>View</a></li>";
         echo "<li class='".active('polling_station_edit')."'><a href='Polling_station_edit.php' Value='Edit'>Edit</a></li>";
         echo "<li class='".active('polling_station_delete')."'><a href='polling_station_delete.php' Value='Delete'>Delete</a></li>";
         echo "</ul>";
      echo "</li>";
      echo "<li class='".active('ps_type_register').active('ps_type_view').active('ps_type_edit').active('ps_type_delete')."'><a href='#'>Polling Station Types</a>";
         echo "<ul>";
         echo "<li class='".active('ps_type_register')."'><a href='ps_type_register.php' Value='Register'>Add</a></li>";
         echo "<li class='".active('ps_type_view')."'><a href='ps_type_view.php' Value='View'>View</a></li>";
         echo "<li class='".active('ps_type_edit')."'><a href='ps_type_edit.php' Value='Edit'>Edit</a></li>";
         echo "<li class='".active('ps_type_delete')."'><a href='ps_type_delete.php' Value='Delete'>Delete</a></li>";
         echo "</ul>";
      echo "</li>";
      echo "<li class='".active('electionrole_register').active('electionrole_view').active('electionrole_edit').active('electionrole_delete')."'><a href='#'>Election Roles</a>";
         echo "<ul>";
         echo "<li class='".active('electionrole_register')."'><a href='electionrole_register.php' Value='Register'>Add</a></li>";
         echo "<li class='".active('electionrole_view')."'><a href='electionrole_view.php' Value='View'>View</a></li>";
         echo "<li class='".active('electionrole_edit')."'><a href='electionrole_edit.php' Value='Edit'>Edit</a></li>";
         echo "<li class='".active('electionrole_delete')."'><a href='electionrole_delete.php' Value='Delete'>Delete</a></li>";
         echo "</ul>";
      echo "</li>";
      echo "<li class='".active('office_register').active('office_view').active('office_edit').active('office_delete')."'><a href='#'>Employee Offices</a>";
         echo "<ul>";
         echo "<li class='".active('office_register')."'><a href='office_register.php' Value='Register'>Add</a></li>";
         echo "<li class='".active('office_view')."'><a href='office_view.php' Value='View'>View</a></li>";
         echo "<li class='".active('office_edit')."'><a href='office_edit.php' Value='Edit'>Edit</a></li>";
         echo "<li class='".active('office_delete')."'><a href='office_delete.php' Value='Delete'>Delete</a></li>";
         echo "</ul>";
      echo "</li>";
      echo "<li class='".active('emp_type_register').active('emp_type_view').active('emp_type_edit').active('emp_type_delete')."'><a href='#'>Employee Types</a>";
         echo "<ul>";
            echo "<li class='".active('emp_type_register')."'><a href='emp_type_register.php' value='register'>Add</a></li>";
            echo "<li class='".active('emp_type_view')."'><a href='emp_type_view.php' Value='View'>View</a></li>";
            echo "<li class='".active('emp_type_edit')."'><a href='emp_type_edit.php' Value='Edit'>Edit</a></li>";
            echo "<li class='".active('emp_type_delete')."'><a href='emp_type_delete.php' Value='Delete'>Delete</a></li>";
         echo "</ul>";
      echo "</li>";
      echo "<li class='".active('emp_office_type_register').active('emp_office_type_view').active('emp_office_type_edit').active('emp_office_type_delete')."'><a href='#'>Employee Office Types</a>";
      echo "<ul>";
         echo "<li class='".active('emp_office_type_register')."'><a href='emp_office_type_register.php' value='register'>Add</a></li>";
         echo "<li class='".active('emp_office_type_view')."'><a href='emp_office_type_view.php' Value='View'>View</a></li>";
         echo "<li class='".active('emp_office_type_edit')."'><a href='emp_office_type_edit.php' Value='Edit'>Edit</a></li>";
         echo "<li class='".active('emp_office_type_delete')."'><a href='emp_office_type_delete.php' Value='Delete'>Delete</a></li>";
      echo "</ul>";
   echo "</li>";
      echo "<li class='".active('gender_register').active('gender_view').active('gender_edit').active('gender_delete')."'><a href='#'>Employee Gender Types</a>";
         echo "<ul>";
         echo "<li class='".active('gender_register')."'><a href='gender_register.php' Value='Register'>Add</a></li>";
         echo "<li class='".active('gender_view')."'><a href='gender_view.php' Value='View'>View</a></li>";
         echo "<li class='".active('gender_edit')."'><a href='gender_edit.php' Value='Edit'>Edit</a></li>";
         echo "<li class='".active('gender_delete')."'><a href='gender_delete.php' Value='Delete'>Delete</a></li>";
        echo "</ul>";
      echo "</li>";
      echo "<li class='".active('emp_dept_register').active('emp_dept_view').active('emp_dept_edit').active('emp_dept_delete')."'><a href='#'>Employee Departments</a>";
      echo "<ul>";
      echo "<li class='".active('emp_dept_register')."'><a href='emp_dept_register.php' Value='Register'>Add</a></li>";
      echo "<li class='".active('emp_dept_view')."'><a href='emp_dept_view.php' Value='View'>View</a></li>";
      echo "<li class='".active('emp_dept_edit')."'><a href='emp_dept_edit.php' Value='Edit'>Edit</a></li>";
      echo "<li class='".active('emp_dept_delete')."'><a href='emp_dept_delete.php' Value='Delete'>Delete</a></li>";
      echo "</ul>";
   echo "</li>";
      /* echo "<li class='".active('')."'><a href='#'>Employee Gazetted Status</a>";
         echo "<ul>";
            echo "<li class='".active('')."'><a href='#'>View</a></li>";
         echo "</ul>";
      echo "</li>";
      */
   echo "</ul>";
echo "</li>";
echo "<li class='".active('emp_register').active('emp_view').active('emp_edit').active('emp_delete')."'><a href='#'>EMPLOYEE DATA</a>";
   echo "<ul>";
   echo "<li class='".active('emp_register')."'><a href='emp_register.php' Value='Register'>Add</a></li>";
   echo "<li class='".active('emp_view')."'><a href='emp_view.php' Value='View'>View</a></li>";
   echo "<li class='".active('emp_edit')."'><a href='emp_edit.php' Value='Edit'>Edit</a></li>";
   echo "<li class='".active('emp_delete')."'><a href='emp_delete.php' Value='Delete'>Delete</a></li>";
   echo "</ul>";
echo "</li>";
echo "<li class='".active('')."'><a href='contact.php'>CONTACT</a></li>";
if(isset($_SESSION["election_id"])){
echo "<li class='".active('change_password').active('logout')."'><a href='#'>ACCOUNT</a>";
   echo "<ul>";
   echo "<li class='".active('change_password')."'><a href='change_password.php'>Change Password</a></li>";
   echo "<li class='".active('logout')."'><a href='logout.php'>Logout</a></li>";
   echo "</ul>";
echo "</li>";
}
//echo "<li class='".active('logout')."'><a href='logout.php'>LOGOUT</a></li>";
echo "</ul>";
echo "</nav>";
echo "<nav>";
echo "<p align='right'><a href='emp_view.php'>User Name: ".$_SESSION["name"]."</a></p>";
echo "</nav>";
?>